[project]
name = "smartsensor"
version = "1.1.0"
description = "The sensor utilizes a smartphone camera to analyze and characterize chemical compounds."
authors = ["Thanh-Giang (River) Tan Nguyen <nttg8100@gmail.com>", "Dung Cao <dung.cao@ttu.edu.vn>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
python = "3.12.*"
pip = ">=25.2,<26"
poetry = ">=2.1.4,<3"

[tasks]
install-dev = "pip install -e ."
install-poetry-deps = "poetry install"
test = "python -m pytest tests/ -v"
lint = "python -m flake8 smartsensor/ && python -m pylint smartsensor/"
format = "python -m black smartsensor/ && python -m isort smartsensor/"
run = "smartsensor"
clean = "find . -name '*.pyc' -delete && find . -name '__pycache__' -type d -exec rm -rf {} + || true"

[feature.dev.dependencies]
pytest = "*"
black = "*"
isort = "*"
flake8 = "*"
pylint = "*"
mypy = "*"
pre-commit = "*"

[environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }
